// Autogenerated with GTP (Generalized Text Preprocessor).
// DO NOT EDIT. Any changes will sooner or later be overwritten.
Shader "FastPaletteSwap/Uber"
{
Properties
{
_MainTex ("Texture", 2D) = "white" {}
_GrayThreshold ("Gray Threshold", Float) = 0.001
_StripeWidth ("Shiny Stripe Width", Float) = 1
_StripeSpacing ("Shiny Stripe Spacing", Float) = 80
_StripeSpeed ("Shiny Stripe Speed", Float) = 500
_PaletteTex0 ("Palette 0", 2D) = "white" {}
_PaletteRow0 ("Palette 0 Row", Integer) = 0
_PaletteTex1 ("Palette 1", 2D) = "white" {}
_PaletteRow1 ("Palette 1 Row", Integer) = 0
_PaletteTex2 ("Palette 2", 2D) = "white" {}
_PaletteRow2 ("Palette 2 Row", Integer) = 0
_PaletteTex3 ("Palette 3", 2D) = "white" {}
_PaletteRow3 ("Palette 3 Row", Integer) = 0
_PaletteTex4 ("Palette 4", 2D) = "white" {}
_PaletteRow4 ("Palette 4 Row", Integer) = 0
_PaletteTex5 ("Palette 5", 2D) = "white" {}
_PaletteRow5 ("Palette 5 Row", Integer) = 0
_PaletteTex6 ("Palette 6", 2D) = "white" {}
_PaletteRow6 ("Palette 6 Row", Integer) = 0
_PaletteTex7 ("Palette 7", 2D) = "white" {}
_PaletteRow7 ("Palette 7 Row", Integer) = 0
_PaletteTex8 ("Palette 8", 2D) = "white" {}
_PaletteRow8 ("Palette 8 Row", Integer) = 0
_PaletteTex9 ("Palette 9", 2D) = "white" {}
_PaletteRow9 ("Palette 9 Row", Integer) = 0
_PaletteTex10 ("Palette 10", 2D) = "white" {}
_PaletteRow10 ("Palette 10 Row", Integer) = 0
_PaletteTex11 ("Palette 11", 2D) = "white" {}
_PaletteRow11 ("Palette 11 Row", Integer) = 0
_PaletteTex12 ("Palette 12", 2D) = "white" {}
_PaletteRow12 ("Palette 12 Row", Integer) = 0
}
SubShader
{
Tags 
{
"Queue" = "Transparent"
"IgnoreProjector" = "True"
"RenderType" = "Transparent"
"PreviewType" = "Plane"
"CanUseSpriteAtlas" = "True"
}
LOD 100
Cull Off
Lighting Off
Zwrite Off
Blend SrcAlpha OneMinusSrcAlpha
Pass
{
CGPROGRAM
#pragma shader_feature_local WATER
#pragma shader_feature_local CH_0
#pragma shader_feature_local CH_0_BG
#pragma shader_feature_local CH_0_BGO
#pragma shader_feature_local CH_0_SHINY
#pragma shader_feature_local CH_0_WALL
#pragma shader_feature_local CH_1
#pragma shader_feature_local CH_1_BG
#pragma shader_feature_local CH_1_BGO
#pragma shader_feature_local CH_1_SHINY
#pragma shader_feature_local CH_1_WALL
#pragma shader_feature_local CH_2
#pragma shader_feature_local CH_2_BG
#pragma shader_feature_local CH_2_BGO
#pragma shader_feature_local CH_2_SHINY
#pragma shader_feature_local CH_2_WALL
#pragma shader_feature_local CH_3
#pragma shader_feature_local CH_3_BG
#pragma shader_feature_local CH_3_BGO
#pragma shader_feature_local CH_3_SHINY
#pragma shader_feature_local CH_3_WALL
#pragma shader_feature_local CH_4
#pragma shader_feature_local CH_4_BG
#pragma shader_feature_local CH_4_BGO
#pragma shader_feature_local CH_4_SHINY
#pragma shader_feature_local CH_4_WALL
#pragma shader_feature_local CH_5
#pragma shader_feature_local CH_5_BG
#pragma shader_feature_local CH_5_BGO
#pragma shader_feature_local CH_5_SHINY
#pragma shader_feature_local CH_5_WALL
#pragma shader_feature_local CH_6
#pragma shader_feature_local CH_6_BG
#pragma shader_feature_local CH_6_BGO
#pragma shader_feature_local CH_6_SHINY
#pragma shader_feature_local CH_6_WALL
#pragma shader_feature_local CH_7
#pragma shader_feature_local CH_7_BG
#pragma shader_feature_local CH_7_BGO
#pragma shader_feature_local CH_7_SHINY
#pragma shader_feature_local CH_7_WALL
#pragma shader_feature_local CH_8
#pragma shader_feature_local CH_8_BG
#pragma shader_feature_local CH_8_BGO
#pragma shader_feature_local CH_8_SHINY
#pragma shader_feature_local CH_8_WALL
#pragma shader_feature_local CH_9
#pragma shader_feature_local CH_9_BG
#pragma shader_feature_local CH_9_BGO
#pragma shader_feature_local CH_9_SHINY
#pragma shader_feature_local CH_9_WALL
#pragma shader_feature_local CH_10
#pragma shader_feature_local CH_10_BG
#pragma shader_feature_local CH_10_BGO
#pragma shader_feature_local CH_10_SHINY
#pragma shader_feature_local CH_10_WALL
#pragma shader_feature_local CH_11
#pragma shader_feature_local CH_11_BG
#pragma shader_feature_local CH_11_BGO
#pragma shader_feature_local CH_11_SHINY
#pragma shader_feature_local CH_11_WALL
#pragma shader_feature_local CH_12
#pragma shader_feature_local CH_12_BG
#pragma shader_feature_local CH_12_BGO
#pragma shader_feature_local CH_12_SHINY
#pragma shader_feature_local CH_12_WALL
#pragma vertex vert
#pragma fragment frag
float _GrayThreshold;
#include "UnityCG.cginc"
#include "logic.cginc"
#include "colorCompare.cginc"
#include "fastPaletteUtils.cginc"
#include "fastPaletteExtraColors.cginc"
struct appdata
{
float4 vertex : POSITION;
float2 uv : TEXCOORD0;
float4 color : COLOR;
};
struct v2f
{
float2 uv : TEXCOORD0;
float4 vertex : SV_POSITION;
float4 color : COLOR;
float3 worldPos : TEXCOORD1;
};
sampler2D _MainTex;
float4 _MainTex_ST;
#include "fastPaletteWalls.cginc"
sampler2D _PaletteTex0;
float4 _PaletteTex0_TexelSize;
int _PaletteRow0;
sampler2D _PaletteTex1;
float4 _PaletteTex1_TexelSize;
int _PaletteRow1;
sampler2D _PaletteTex2;
float4 _PaletteTex2_TexelSize;
int _PaletteRow2;
sampler2D _PaletteTex3;
float4 _PaletteTex3_TexelSize;
int _PaletteRow3;
sampler2D _PaletteTex4;
float4 _PaletteTex4_TexelSize;
int _PaletteRow4;
sampler2D _PaletteTex5;
float4 _PaletteTex5_TexelSize;
int _PaletteRow5;
sampler2D _PaletteTex6;
float4 _PaletteTex6_TexelSize;
int _PaletteRow6;
sampler2D _PaletteTex7;
float4 _PaletteTex7_TexelSize;
int _PaletteRow7;
sampler2D _PaletteTex8;
float4 _PaletteTex8_TexelSize;
int _PaletteRow8;
sampler2D _PaletteTex9;
float4 _PaletteTex9_TexelSize;
int _PaletteRow9;
sampler2D _PaletteTex10;
float4 _PaletteTex10_TexelSize;
int _PaletteRow10;
sampler2D _PaletteTex11;
float4 _PaletteTex11_TexelSize;
int _PaletteRow11;
sampler2D _PaletteTex12;
float4 _PaletteTex12_TexelSize;
int _PaletteRow12;
float _MS_WaterLevel;
int _MS_WallsPaletteRow;
v2f vert (appdata v)
{
v2f o;
o.vertex = UnityObjectToClipPos(v.vertex);
o.uv = TRANSFORM_TEX(v.uv, _MainTex);
o.color = v.color;
o.worldPos = mul(unity_ObjectToWorld, v.vertex);
return o;
}
float4 frag (v2f i) : SV_Target
{
float4 col = tex2D(_MainTex, i.uv);
float alpha = col.a;
float underwater = 0.0;
if (WATER)
{
underwater = i.worldPos.y <= _MS_WaterLevel;
}
float4 tmpColor;
float4 newColor = col;
int row;
if (CH_0)
{
    if (CH_0_BG)
    {
        tmpColor = getBackgroundColor(col.r, _PaletteTex0_TexelSize, _PaletteRow0, underwater, _PaletteTex0);
    }
    else if (CH_0_BGO)
    {
        tmpColor = getBGOColor(col.r, _PaletteTex0_TexelSize, _PaletteRow0, underwater, _PaletteTex0);
    }
    else if (CH_0_SHINY)
    {
        row = _PaletteRow0 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.r, _PaletteTex0_TexelSize, row, underwater, _PaletteTex0);
    }
    else if (CH_0_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex0_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex0);
    }
    else
    {
        tmpColor = getColor(col.r, _PaletteTex0_TexelSize, _PaletteRow0, underwater, _PaletteTex0);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
if (CH_1)
{
    if (CH_1_BG)
    {
        tmpColor = getBackgroundColor(col.r, _PaletteTex1_TexelSize, _PaletteRow1, underwater, _PaletteTex1);
    }
    else if (CH_1_BGO)
    {
        tmpColor = getBGOColor(col.r, _PaletteTex1_TexelSize, _PaletteRow1, underwater, _PaletteTex1);
    }
    else if (CH_1_SHINY)
    {
        row = _PaletteRow1 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.r, _PaletteTex1_TexelSize, row, underwater, _PaletteTex1);
    }
    else if (CH_1_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex1_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex1);
    }
    else
    {
        tmpColor = getColor(col.r, _PaletteTex1_TexelSize, _PaletteRow1, underwater, _PaletteTex1);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
if (CH_2)
{
    if (CH_2_BG)
    {
        tmpColor = getBackgroundColor(col.g, _PaletteTex2_TexelSize, _PaletteRow2, underwater, _PaletteTex2);
    }
    else if (CH_2_BGO)
    {
        tmpColor = getBGOColor(col.g, _PaletteTex2_TexelSize, _PaletteRow2, underwater, _PaletteTex2);
    }
    else if (CH_2_SHINY)
    {
        row = _PaletteRow2 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.g, _PaletteTex2_TexelSize, row, underwater, _PaletteTex2);
    }
    else if (CH_2_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex2_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex2);
    }
    else
    {
        tmpColor = getColor(col.g, _PaletteTex2_TexelSize, _PaletteRow2, underwater, _PaletteTex2);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
if (CH_3)
{
    if (CH_3_BG)
    {
        tmpColor = getBackgroundColor(col.b, _PaletteTex3_TexelSize, _PaletteRow3, underwater, _PaletteTex3);
    }
    else if (CH_3_BGO)
    {
        tmpColor = getBGOColor(col.b, _PaletteTex3_TexelSize, _PaletteRow3, underwater, _PaletteTex3);
    }
    else if (CH_3_SHINY)
    {
        row = _PaletteRow3 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.b, _PaletteTex3_TexelSize, row, underwater, _PaletteTex3);
    }
    else if (CH_3_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex3_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex3);
    }
    else
    {
        tmpColor = getColor(col.b, _PaletteTex3_TexelSize, _PaletteRow3, underwater, _PaletteTex3);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
if (CH_4)
{
    if (CH_4_BG)
    {
        tmpColor = getBackgroundColor(col.b, _PaletteTex4_TexelSize, _PaletteRow4, underwater, _PaletteTex4);
    }
    else if (CH_4_BGO)
    {
        tmpColor = getBGOColor(col.b, _PaletteTex4_TexelSize, _PaletteRow4, underwater, _PaletteTex4);
    }
    else if (CH_4_SHINY)
    {
        row = _PaletteRow4 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.b, _PaletteTex4_TexelSize, row, underwater, _PaletteTex4);
    }
    else if (CH_4_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex4_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex4);
    }
    else
    {
        tmpColor = getColor(col.b, _PaletteTex4_TexelSize, _PaletteRow4, underwater, _PaletteTex4);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
if (CH_5)
{
    if (CH_5_BG)
    {
        tmpColor = getBackgroundColor(col.r, _PaletteTex5_TexelSize, _PaletteRow5, underwater, _PaletteTex5);
    }
    else if (CH_5_BGO)
    {
        tmpColor = getBGOColor(col.r, _PaletteTex5_TexelSize, _PaletteRow5, underwater, _PaletteTex5);
    }
    else if (CH_5_SHINY)
    {
        row = _PaletteRow5 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.r, _PaletteTex5_TexelSize, row, underwater, _PaletteTex5);
    }
    else if (CH_5_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex5_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex5);
    }
    else
    {
        tmpColor = getColor(col.r, _PaletteTex5_TexelSize, _PaletteRow5, underwater, _PaletteTex5);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
if (CH_6)
{
    if (CH_6_BG)
    {
        tmpColor = getBackgroundColor(col.r, _PaletteTex6_TexelSize, _PaletteRow6, underwater, _PaletteTex6);
    }
    else if (CH_6_BGO)
    {
        tmpColor = getBGOColor(col.r, _PaletteTex6_TexelSize, _PaletteRow6, underwater, _PaletteTex6);
    }
    else if (CH_6_SHINY)
    {
        row = _PaletteRow6 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.r, _PaletteTex6_TexelSize, row, underwater, _PaletteTex6);
    }
    else if (CH_6_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex6_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex6);
    }
    else
    {
        tmpColor = getColor(col.r, _PaletteTex6_TexelSize, _PaletteRow6, underwater, _PaletteTex6);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
if (CH_7)
{
    if (CH_7_BG)
    {
        tmpColor = getBackgroundColor(col.r, _PaletteTex7_TexelSize, _PaletteRow7, underwater, _PaletteTex7);
    }
    else if (CH_7_BGO)
    {
        tmpColor = getBGOColor(col.r, _PaletteTex7_TexelSize, _PaletteRow7, underwater, _PaletteTex7);
    }
    else if (CH_7_SHINY)
    {
        row = _PaletteRow7 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.r, _PaletteTex7_TexelSize, row, underwater, _PaletteTex7);
    }
    else if (CH_7_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex7_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex7);
    }
    else
    {
        tmpColor = getColor(col.r, _PaletteTex7_TexelSize, _PaletteRow7, underwater, _PaletteTex7);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
if (CH_8)
{
    if (CH_8_BG)
    {
        tmpColor = getBackgroundColor(col.r, _PaletteTex8_TexelSize, _PaletteRow8, underwater, _PaletteTex8);
    }
    else if (CH_8_BGO)
    {
        tmpColor = getBGOColor(col.r, _PaletteTex8_TexelSize, _PaletteRow8, underwater, _PaletteTex8);
    }
    else if (CH_8_SHINY)
    {
        row = _PaletteRow8 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.r, _PaletteTex8_TexelSize, row, underwater, _PaletteTex8);
    }
    else if (CH_8_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex8_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex8);
    }
    else
    {
        tmpColor = getColor(col.r, _PaletteTex8_TexelSize, _PaletteRow8, underwater, _PaletteTex8);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
if (CH_9)
{
    if (CH_9_BG)
    {
        tmpColor = getBackgroundColor(col.r, _PaletteTex9_TexelSize, _PaletteRow9, underwater, _PaletteTex9);
    }
    else if (CH_9_BGO)
    {
        tmpColor = getBGOColor(col.r, _PaletteTex9_TexelSize, _PaletteRow9, underwater, _PaletteTex9);
    }
    else if (CH_9_SHINY)
    {
        row = _PaletteRow9 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.r, _PaletteTex9_TexelSize, row, underwater, _PaletteTex9);
    }
    else if (CH_9_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex9_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex9);
    }
    else
    {
        tmpColor = getColor(col.r, _PaletteTex9_TexelSize, _PaletteRow9, underwater, _PaletteTex9);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
if (CH_10)
{
    if (CH_10_BG)
    {
        tmpColor = getBackgroundColor(col.g, _PaletteTex10_TexelSize, _PaletteRow10, underwater, _PaletteTex10);
    }
    else if (CH_10_BGO)
    {
        tmpColor = getBGOColor(col.g, _PaletteTex10_TexelSize, _PaletteRow10, underwater, _PaletteTex10);
    }
    else if (CH_10_SHINY)
    {
        row = _PaletteRow10 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.g, _PaletteTex10_TexelSize, row, underwater, _PaletteTex10);
    }
    else if (CH_10_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex10_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex10);
    }
    else
    {
        tmpColor = getColor(col.g, _PaletteTex10_TexelSize, _PaletteRow10, underwater, _PaletteTex10);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
if (CH_11)
{
    if (CH_11_BG)
    {
        tmpColor = getBackgroundColor(col.g, _PaletteTex11_TexelSize, _PaletteRow11, underwater, _PaletteTex11);
    }
    else if (CH_11_BGO)
    {
        tmpColor = getBGOColor(col.g, _PaletteTex11_TexelSize, _PaletteRow11, underwater, _PaletteTex11);
    }
    else if (CH_11_SHINY)
    {
        row = _PaletteRow11 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.g, _PaletteTex11_TexelSize, row, underwater, _PaletteTex11);
    }
    else if (CH_11_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex11_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex11);
    }
    else
    {
        tmpColor = getColor(col.g, _PaletteTex11_TexelSize, _PaletteRow11, underwater, _PaletteTex11);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
if (CH_12)
{
    if (CH_12_BG)
    {
        tmpColor = getBackgroundColor(col.b, _PaletteTex12_TexelSize, _PaletteRow12, underwater, _PaletteTex12);
    }
    else if (CH_12_BGO)
    {
        tmpColor = getBGOColor(col.b, _PaletteTex12_TexelSize, _PaletteRow12, underwater, _PaletteTex12);
    }
    else if (CH_12_SHINY)
    {
        row = _PaletteRow12 + 2 * isShine(i.worldPos);
        tmpColor = getColor(col.b, _PaletteTex12_TexelSize, row, underwater, _PaletteTex12);
    }
    else if (CH_12_WALL)
    {
        tmpColor = getWallColor(i, _PaletteTex12_TexelSize, _MS_WallsPaletteRow, underwater, _PaletteTex12);
    }
    else
    {
        tmpColor = getColor(col.b, _PaletteTex12_TexelSize, _PaletteRow12, underwater, _PaletteTex12);
    }
    newColor = lerp(newColor, tmpColor, isGray(col));
}
newColor *= i.color;
newColor.a *= alpha;
return newColor;
}
ENDCG
}
}
CustomEditor "Muketronics.VFX.FastPaletteSwapUberGUI"
}
