start: statement*

statement: command
      | enclosure
      | for_loop

command: (assignment
      | echo) ";"

assignment: variable "=" value

echo: "echo" value

enclosure: "{" statement* "}"

for_loop: "for" variable "=" value "," value enclosure

variable: CNAME

value: variable
      | literal
      | f_string
      | array
      | indexer

literal: STRING
      | INT

STRING: /'([^'\\]|\\.)*'/
      | /"([^"\\]|\\.)*"/

INT: /-?\d+/

f_string: "f'" (F_STRING_INNER | "{" value "}")* "'"
      | "f\"" (F_STRING_INNER_2 | "{" value "}")* "\""

F_STRING_INNER: /([^'\{\\]|\\.)+/
F_STRING_INNER_2: /([^"\{\\]|\\.)+/

array: "{" ((value ",")* value ","?)? "}"

indexer: variable "[" value "]"

%import common (NEWLINE, CNAME, WS)

%ignore WS
