start: statement*

statement: command
      | enclosure
      | for_loop
      | conditional

command: (assignment
      | echo) ";"

assignment: variable "=" value

echo: "echo" value

enclosure: "{" statement* "}"

for_loop: "for" variable "=" value "," value enclosure

conditional: "if" value enclosure ("elif" value enclosure)* ("else" enclosure)?

value: variable
      | literal
      | f_string
      | array
      | indexer
      | binary_operation

literal.2: STRING
      | INT
      | BOOL

STRING: /'([^'\\]|\\.)*'/
      | /"([^"\\]|\\.)*"/

INT: /-?\d+/

BOOL: "true" | "false"

variable: CNAME

f_string: "f'" (F_STRING_INNER | "{" value "}")* "'"
      | "f\"" (F_STRING_INNER_2 | "{" value "}")* "\""

F_STRING_INNER: /([^'\{\\]|\\.)+/
F_STRING_INNER_2: /([^"\{\\]|\\.)+/

array: "{" ((value ",")* value ","?)? "}"

indexer: variable "[" value "]"

binary_operation: value BINARY_OP value

BINARY_OP: "=="

%import common (NEWLINE, CNAME, WS)

%ignore WS
