?start: statement*

?statement: enclosure
    | (operation ";")

?enclosure: conditional
    | iterator_loop
    | scope

conditional: "if" operation scope ("elif" operation scope)* ("else" scope)?

// Iterate over range or array; error for any other type
iterator_loop: "for" variable "in" operation scope

scope: "{" statement* "}"

operation: expression

// Everything above this point is processed top-down
// Everything below this point is processed bottom-up

// Rules containing keywords must be defined before the variable rule, or the keywords will all be misinterpreted as 
// variable names (rules are matched using a depth-first traversal).

?expression: "echo" assignment -> print
    | assignment

?assignment: conjunction
    | assignable "="  assignment -> set_value
    | assignable "+=" assignment -> iadd
    | assignable "-=" assignment -> isub
    | assignable "*=" assignment -> imul
    | assignable "/=" assignment -> idiv
    | assignable "%=" assignment -> imod
    | assignable "^=" assignment -> ipow

?assignable: variable
    | indexer

?conjunction: conjunction "and" comparison -> and_
    | conjunction "or" comparison -> or_
    | comparison

?comparison: sum
    | comparison "==" sum -> eq
    | comparison "!=" sum -> ne
    | comparison "<=" sum -> le
    | comparison ">=" sum -> ge
    | comparison "<" sum -> lt
    | comparison ">" sum -> gt

?sum: product
    | sum "+" product -> add
    | sum "-" product -> sub

?product: power
    | product "*" power -> mul
    | product "/" power -> div
    | product "%" power -> mod
    
?power: unary
    | power "^" unary -> pow

?unary: "not" atom -> not_
    | atom
    | "-" atom -> neg
    | "++" atom -> pre_inc
    | "--" atom -> pre_dec
    | atom "++" -> post_inc
    | atom "--" -> post_dec

?atom: literal
    | value_range
    | variable
    | f_string
    | array
    | indexer
    | "(" expression ")"

variable: CNAME

?literal: integer
    | string
    | boolean
    | null

integer: SIGNED_INT

string: /'([^'\\]|\\.)*'/
    | /"([^"\\]|\\.)*"/

boolean: TRUE | FALSE

TRUE: "true"
FALSE: "false"

null: "null"

f_string: "f'" (F_STRING_INNER | "{" operation "}")* "'"
      | "f\"" (F_STRING_INNER_2 | "{" operation "}")* "\""

array: "{" operation? ("," operation)* "}"

indexer: variable "[" operation "]"

value_range: "range(" operation ("," operation) ~ 0..2 ")"

F_STRING_INNER: /([^'\{\\]|\\.)+/ | WS
F_STRING_INNER_2: /([^"\{\\]|\\.)+/ | WS

%import common (SIGNED_INT, CNAME, WS)

%ignore WS
